export const toAreas = [
  "Canchipur",
  "Kakwa",
  "Singjamei",
  "Moirangkhong",
  "Paona Bazar",
  "Khongman",
  "Kongba",
  "Bamon Leikai",
  "Wangkhei",
  "Ayangpalli Rd",
  "Porompat DC",
  "Konung Mamang",
  "Checkon",
  "Khurai",
  "Khurai Heikrumakhong",
  "Nagaram",
  "Mantripukhri",
  "Chingmeirong",
  "North AOC",
  "Thangal Bazar",
  "Game Village/ Langol",
  "Thangmeiband",
  "Lamphel",
  "Nagamapal",
  "Uripok",
  "Naoremthong",
  "Sagolband",
  "Langjing",
  "Malom",
  "Ghari",
  "Sangaiporou",
  "Kwakeithel",
  "Keisampat",
  "Keisamthong",
  "Pishum",
  "Heiranggoi Thong",
  "Mongsanggei",
];

export const fromAreas = [
  "Canchipur",
  "Kakwa",
  "Singjamei",
  "Moirangkhong",
  "Paona Bazar",
  "Khongman",
  "Kongba",
  "Bamon Leikai",
  "Wangkhei",
  "Ayangpalli Road",
  "Porompat",
  "Konung mamang",
  "Checkon",
  "Khurai Lamlong",
  "Khurai Heikrumakhong",
  "Nagaram",
  "Mantripukhri",
  "Chingmeirong",
  "North AOC",
  "Thangal Bazar",
  "Langol",
  "Thangmeiband",
  "Lamphel",
  "Nagamapal",
  "Uripok",
  "Naoremthong",
  "Sagolband",
  "Langjing",
  "Malom",
  "Ghari",
  "Sangaiporou",
  "Kwakeithel",
  "Keisampat",
  "Keisamthong",
  "Pishum",
  "Heiranggoi Thong",
  "Mongsanggei",
];
